version: '3'
services:
  flask_app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    networks:
      - public_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - private_network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - private_network
    volumes:
      - grafana-storage:/var/lib/grafana

networks:
  public_network:
    driver: bridge
  private_network:
    driver: bridge

volumes:
  grafana-storage:

